services:

  backend:
    build: .
    ports:
      - "3000:3000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:jai20012007@postgres:5432/orderdb

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jai20012007
      POSTGRES_DB: orderdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: